name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

  ansible:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Ansible Syntax Check
        run: ansible-playbook -i inventory.ini playbook.yml --syntax-check

  kubernetes:
    name: Kubernetes YAML Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yamllint and kubeval
        run: |
          sudo apt-get update
          sudo apt-get install -y curl yamllint
          curl -Lo kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar -xzf kubeval.tar.gz
          chmod +x kubeval
          sudo mv kubeval /usr/local/bin/

      - name: YAML Lint
        run: yamllint .

      - name: Kubeval Validation
        run: kubeval *.yaml

